version: '3'
services:
  derivatives:
    build: .
    volumes:
      - /path/to/warcs:/in:ro
      - /path/to/store/results:/out:rw
    command: >-
      /spark/bin/spark-submit
      --driver-memory 5G
      --py-files /aut/aut-0.90.2.zip
      --jars /aut/aut-0.90.2-fatjar.jar
      /extract/main.py
      --target-instance-list /out/TargetInstanceIDs
      --type noboilerplate
